title: fio
description: axboe/fio 的静态构建 (跨平台单二进制, I/O 性能测试工具)
repo: fio
baseurl: ""
url: "https://fio.ljh.sh"
theme: ~

permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
